---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Allow Nginx Proxy Manager admin UI
  ufw:
    rule: allow
    port: "81"
    proto: tcp

- name: Allow Portainer HTTPS UI
  ufw:
    rule: allow
    port: "9443"
    proto: tcp

- name: Allow Semaphore UI
  ufw:
    rule: allow
    port: "3001"
    proto: tcp

- name: Allow Jenkins web UI
  ufw:
    rule: allow
    port: "8080"
    proto: tcp

- name: Allow MERN application frontend
  ufw:
    rule: allow
    port: "{{ app_external_frontend_port }}"
    proto: tcp

- name: Allow MERN application backend API
  ufw:
    rule: allow
    port: "{{ app_external_backend_port }}"
    proto: tcp

- name: Allow Grafana UI
  ufw:
    rule: allow
    port: "3000"
    proto: tcp

- name: Allow Prometheus UI
  ufw:
    rule: allow
    port: "9090"
    proto: tcp

- name: Allow Alertmanager UI
  ufw:
    rule: allow
    port: "9093"
    proto: tcp

- name: Allow Node Exporter metrics
  ufw:
    rule: allow
    port: "9100"
    proto: tcp

- name: Allow Blackbox Exporter metrics
  ufw:
    rule: allow
    port: "9115"
    proto: tcp

- name: Allow Jenkins agent connections
  ufw:
    rule: allow
    port: "50000"
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
