FROM node:20-alpine

WORKDIR /app

# Install dependencies required by bcrypt (native addon)
RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE ${PORT}

CMD ["node", "--watch", "server.js"]
